openapi: 3.0.0
info:
  title: Transaction Service API
  version: 1.0.0

servers:
  - url: http://localhost/api/v1

paths:
  /transactions/account:
    post:
      summary: Create transaction for accounts
      operationId: createTransactionAccounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountTransactionRequest'
      responses:
        '201':
          description: Account transaction created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountTransactionResponse'

  /transactions/credit-card:
    post:
      summary: Create transaction for credit cards
      operationId: createTransactionCreditCard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditCardTransactionRequest'
      responses:
        '201':
          description: Credit card transaction created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardTransactionResponse'

  /transactions/account/by-account/{accountNumber}:
    get:
      summary: Get transactions by account
      operationId: getTransactionsByAccount
      parameters:
        - name: accountNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountTransactionResponse'
components:
  schemas:
    AccountTransactionRequest:
      type: object
      properties:
        originAccountNumber:
          type: string
          minLength: 1
          maxLength: 40
        destinationAccountNumber:
          type: string
          minLength: 1
          maxLength: 40
        type:
          type: string
          minLength: 1
        amount:
          type: number
        description:
          type: string
      required:
        - destinationAccountNumber
        - type
        - amount

    CreditCardTransactionRequest:
      type: object
      properties:
        creditCard:
          type: string
        customerId:
          type: string
        amount:
          type: number
        description:
          type: string
      required:
        - creditCard
        - customerId
        - amount

    CreditCardTransactionResponse:
      type: object
      properties:
        creditCard:
          type: string
        customerId:
          type: string
        amount:
          type: number
        description:
          type: string

    AccountTransactionResponse:
      type: object
      properties:
        id:
          type: string
        originAccountNumber:
          type: string
        destinationAccountNumber:
          type: string
        type:
          type: string
        amount:
          type: number
        date:
          type: string
          format: date-time
        description:
          type: string

    AccountPatchRequest:
      type: object
      properties:
        status:
          type: string
        balance:
          type: number
        monthlyMovements:
          type: integer

    CreditCardPatchRequest:
      type: object
      properties:
        usedAmount:
          type: number
        creditLimit:
          type: number

    AccountResponse:
      type: object
      properties:
        id:
          type: string
        accountNumber:
          type: string
        accountType:
          type: string
        balance:
          type: number
        customerId:
          type: string
        creationDate:
          type: string
          format: date-time
        status:
          type: string
        monthlyMovements:
          type: integer
        maintenanceFee:
          type: number
          format: double
        endDay:
          type: string
          format: date-time
        availableDayForMovements:
          type: integer
        maxMonthlyMovements:
          type: integer

    CreditCardResponse:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        creditLimit:
          type: number
        cardNumber:
          type: string
        usedAmount:
          type: number
        creditCardStatus:
          type: string

    ResponseBase:
      type: object
      properties:
        message:
          type: string