openapi: 3.0.0
info:
  title: Transaction Service API
  version: 1.0.0

servers:
  - url: http://localhost/api/v1

paths:
  /transactions/account:
    post:
      summary: Create transaction for accounts
      operationId: createTransactionAccounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountTransactionRequest'
      responses:
        '201':
          description: Account transaction created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountTransactionResponse'

  /transactions/account/by-account/{accountNumber}:
    get:
      summary: Get transactions by account
      operationId: getTransactionsByAccount
      parameters:
        - name: accountNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountTransactionResponse'

  /transactions/credit-card/usage:
    post:
      summary: Create an usage transaction for credit cards
      operationId: createCreditCardUsageTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditCardUsageTransactionRequest'
      responses:
        '201':
          description: Credit card transaction created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardUsageTransactionResponse'

  /transactions/credit/payment:
    post:
      summary: Create a payment transaction for credit
      operationId: createCreditPaymentTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditPaymentTransactionRequest'
      responses:
        '201':
          description: Credit payment transaction created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditPaymentTransactionResponse'

  /transactions/customer-products/dni/{dni}:
    get:
      summary: Get all the customer bank products
      operationId: getAllCustomerProductsByDni
      parameters:
        - name: dni
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of all customer products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerProductsResponse'

  /transactions/customer-products/ruc/{ruc}:
    get:
      summary: Get all the customer bank products
      operationId: getAllCustomerProductsByRuc
      parameters:
        - name: ruc
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of all customer products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerProductsResponse'

components:
  schemas:
    CustomerProductsResponse:
      type: object
      properties:
        customer:
          $ref: "#/components/schemas/CustomerResponse"
        accounts:
          type: array
          items:
            $ref: "#/components/schemas/AccountResponse"
        creditCards:
          type: array
          items:
            $ref: "#/components/schemas/CreditCardResponse"

    AccountTransactionRequest:
      type: object
      properties:
        originAccountNumber:
          type: string
          minLength: 1
          maxLength: 40
        destinationAccountNumber:
          type: string
          minLength: 1
          maxLength: 40
        type:
          type: string
          minLength: 1
        amount:
          type: number
        description:
          type: string
      required:
        - originAccountNumber
        - type
        - amount

    CreditCardUsageTransactionRequest:
      type: object
      properties:
        creditCard:
          type: string
        customerId:
          type: string
        amount:
          type: number
        description:
          type: string
      required:
        - creditCard
        - customerId
        - amount

    CreditCardUsageTransactionResponse:
      type: object
      properties:
        creditCard:
          type: string
        customerId:
          type: string
        amount:
          type: number
        description:
          type: string

    CreditPaymentTransactionRequest:
      type: object
      properties:
        creditId:
          type: string
      required:
        - creditId
        - customerId
        - amount

    CreditPaymentTransactionResponse:
      type: object
      properties:
        creditId:
          type: string

    CreditPatchRequest:
      type: object
      properties:
        amountPaid:
          type: number
      required:
        - amountPaid

    AccountTransactionResponse:
      type: object
      properties:
        id:
          type: string
        originAccountNumber:
          type: string
        destinationAccountNumber:
          type: string
        type:
          type: string
        amount:
          type: number
        date:
          type: string
          format: date-time
        description:
          type: string

    AccountPatchRequest:
      type: object
      properties:
        status:
          type: string
        balance:
          type: number
        monthlyMovements:
          type: integer

    CreditCardPatchRequest:
      type: object
      properties:
        usedAmount:
          type: number
        creditLimit:
          type: number

    AccountResponse:
      type: object
      properties:
        id:
          type: string
        accountNumber:
          type: string
        accountType:
          type: string
        balance:
          type: number
        customerId:
          type: string
        creationDate:
          type: string
          format: date-time
        status:
          type: string
        monthlyMovements:
          type: integer
        maintenanceFee:
          type: number
          format: double
        endDay:
          type: string
          format: date-time
        availableDayForMovements:
          type: integer
        maxMonthlyMovements:
          type: integer
        customerType:
          type: string
        maxMonthlyMovementsNoFee:
          type: integer
        transactionCommissionFeePercentage:
          type: number

    CreditCardResponse:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        creditLimit:
          type: number
        cardNumber:
          type: string
        usedAmount:
          type: number
        creditCardStatus:
          type: string

    CreditResponse:
      type: object
      properties:
        clientId:
          type: string
        amount:
          type: number
        status:
          type: string
        interestRate:
          type: number
        termInMonths:
          type: integer
        monthlyPayment:
          type: number
        amountPaid:
          type: number
        totalAmount:
          type: number

    CustomerResponse:
      type: object
      properties:
        id:
          type: string
        documentNumber:
          type: string
        ruc:
          type: string
        businessName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        type:
          type: string
        status:
          type: string

    ResponseBase:
      type: object
      properties:
        message:
          type: string